### ISSUE TITLE
Policy Rule Application Refactor

### ISSUE THREAD

**Issue by zimventures** [mantiumai/chirps#154]
The existing `Policy` and `PolicyVersion` models will not be modified. What's changing here are the `Rule`'s that belong to a policy. A new `BaseRule` class will contain the `name`, `severity` and `policy` fields.

A new `RegexRule` model will be created to move regular expression specific values out of the existing `Rule` model. It will contain `query_string`, `query_embedding`, and `regex_test` fields.

Additional rule types will be crafted to support the new LLM Scanning and DDOS Vulnerability functionality.

**Comment by alex-nork** [comment]
Closed by #169
