### ISSUE TITLE
APIEndpointAsset

### ISSUE THREAD

**Issue by zimventures** [mantiumai/chirps#158]
In order to scan chat bots, a generic API endpoint asset will be needed. It's expected that an API Endpoint will issue an HTTP GET or POST request to a URL, receive a response, and then return that to the caller. 

# Authentication
For the initial implementation, this asset will support either HTTP-basic auth or Bearer Token auth.

# Endpoint 
The user will configure a URL to be hit as a POST request

# Headers
Any headers that are needed to be part of the HTTP POST must be configurable here as well

# Body
For the body, JSON is expected to be the specified format. A template variable `%query%` will be placed in the body so that Chirps knows where to place the query data. 

Example:
```json
{'data': '%query%'}
```

# Response
For now, the entire response body will be passed back to the caller.

**Comment by alex-nork** [comment]
Closed by #165
