### ISSUE TITLE
Development Documentation Enhancements

### ISSUE THREAD

**Issue by zimventures** [mantiumai/chirps#79]
The architecture diagram found in https://chirps.mantiumai.com/development/ is not showing.

In addition, the section `in-dev` needs to be fleshed out. This section includes the user-provided scanning functionality.

**Comment by alex-nork** [comment]
We can also include in this issue documentation updates to reflect recent refactoring around scans, policies, and assets.

**Comment by alex-nork** [comment]
Closed by #104 and #103
